import type { Metadata } from "next";
import "./globals.css";
import Header from "./ComponentsUi/Header";
import Footer from "./ComponentsUi/Footer";

// ✅ Use a supported Google Font instead of Geist
import { Inter } from "next/font/google";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SOP Provider App",
  description: "Generated by SOP Provider",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
